//+------------------------------------------------------------------+
//|                                     Signals/SignalPublisher.mqh   |
//+------------------------------------------------------------------+
#ifndef SIGNALPUBLISHER_MQH
#define SIGNALPUBLISHER_MQH
#include "../Decision/TradeDecision.mqh"
#include "SubscriberPlatform.mqh"
#include "../Core/PipCalculator.mqh"
class CSignalPublisher
  {
private:
   string m_filename; int m_fileHandle; long m_lastPublishedId; CSubscriberPlatform* m_platform; int m_timeoutMs; string m_apiKey; string m_weightVersion;
   bool TransmitOne(string endpoint,const string &payload); bool TransmitOnePatch(string endpoint,const string &payload); string BuildJsonPayload(const TradeDecisionRecord &dec); string BuildReasonsJsonArray(const SetupReasons &r); string BuildExtraJson(const TradeDecisionRecord &dec); string SignalIdFor(long decisionId);
   string BuildOutcomeJsonPayload(string signalId,string symbol,string direction,string outcome,double realizedR,double mfeR,double maeR,int barsHeld,int barsToFill,bool filled,string regime,string session,string sweepGrade,bool htfObAligned,double confidenceAtSignal,double confidenceDecayed,int decayBars);
public:
   void Init(string symbol,CSubscriberPlatform* platform,int timeoutMs=5000,string apiKey=""); void Deinit(); bool Publish(const TradeDecisionRecord &dec); bool PublishStatusUpdate(long decisionId,string status,string reason); bool PublishOutcome(string signalId,string symbol,string direction,string outcome,double realizedR,double mfeR,double maeR,int barsHeld,int barsToFill,bool filled,string regime,string session,string sweepGrade,bool htfObAligned,double confidenceAtSignal,double confidenceDecayed,int decayBars); void SetWeightVersion(string v){m_weightVersion=v;} string SignalIdForDecision(long decisionId){return SignalIdFor(decisionId);}
  };
void CSignalPublisher::Init(string symbol,CSubscriberPlatform* platform,int timeoutMs,string apiKey){m_lastPublishedId=0;m_platform=platform;m_timeoutMs=timeoutMs;m_apiKey=apiKey;m_weightVersion="";m_filename="MedisTouch_SignalFeed_"+symbol+".csv";bool exists=FileIsExist(m_filename);m_fileHandle=FileOpen(m_filename,FILE_READ|FILE_WRITE|FILE_CSV,',');if(m_fileHandle==INVALID_HANDLE){Print("MedisTouch SignalPublisher: could not open ",m_filename);return;}FileSeek(m_fileHandle,0,SEEK_END);if(!exists)FileWrite(m_fileHandle,"DecisionID","Time","Symbol","Direction","Entry","SL","TP1","TP2","FinalTP","Confidence","Action","SubscribersTargeted","SubscribersDelivered");}
void CSignalPublisher::Deinit(){if(m_fileHandle!=INVALID_HANDLE)FileClose(m_fileHandle);}
string CSignalPublisher::SignalIdFor(long decisionId){return "MT#"+IntegerToString(decisionId);}
string CSignalPublisher::BuildReasonsJsonArray(const SetupReasons &r){string items[];int n=0;#define MT_ADD_REASON(cond,txt) if(cond){ArrayResize(items,n+1);items[n++]=txt;}
   MT_ADD_REASON(r.trend_aligned,"HTF trend aligned") MT_ADD_REASON(r.inducement_valid,"Inducement sequence confirmed") MT_ADD_REASON(r.liquidity_swept,"Liquidity swept") MT_ADD_REASON(r.bos_confirmed,"BOS confirmed") MT_ADD_REASON(r.fresh_fvg,"Fresh FVG in zone") MT_ADD_REASON(r.sr_confluence,"S/R confluence") MT_ADD_REASON(r.premium_discount_ok,"Premium/discount location OK") MT_ADD_REASON(r.volume_confirmed,"Volume confirmed") MT_ADD_REASON(r.fib_in_zone,"Fibonacci zone confluence") MT_ADD_REASON(r.value_area_ok,"Value area location OK") MT_ADD_REASON(r.htf_ob_confluence,"HTF order block confluence") #undef MT_ADD_REASON
   if(n==0){ArrayResize(items,1);items[0]="Confluence-based setup";n=1;}string json="[";for(int i=0;i<n;i++){string esc=items[i];StringReplace(esc,"\"","'");json+="\""+esc+"\"";if(i<n-1)json+=",";}json+="]";return json;}
string CSignalPublisher::BuildExtraJson(const TradeDecisionRecord &dec){SetupReasons r=dec.setup.reasons;string symbol=dec.symbol;double pip=CPipCalculator::PipSize(symbol);bool isBuy=(dec.setup.type==ORDER_TYPE_BUY);double entry=isBuy?dec.setup.entry_top:dec.setup.entry_bottom;double pipsSl=(pip>0)?MathAbs(entry-dec.setup.stop_loss)/pip:0.0;double pipsTp1=(pip>0)?MathAbs(dec.setup.tp1-entry)/pip:0.0;double pipsTp2=(pip>0)?MathAbs(dec.setup.tp2-entry)/pip:0.0;double rrTp1=(pipsSl>0)?pipsTp1/pipsSl:0.0;double rrTp2=(pipsSl>0)?pipsTp2/pipsSl:0.0;return StringFormat("{\"pips_sl\":%.1f,\"pips_tp1\":%.1f,\"pips_tp2\":%.1f,\"rr_tp1\":%.2f,\"rr_tp2\":%.2f,\"sweep_grade\":\"%s\",\"bos_strength\":%.1f,\"time_decay\":%.1f,\"chase_dist_atr\":%.2f,\"chase_ok\":%s,\"news_risk\":\"%s\",\"news_label\":\"%s\",\"news_minutes_to_event\":%d,\"calibrated_probability\":%.1f,\"calibration_sample\":%d,\"calibration_has_enough_data\":%s}",pipsSl,pipsTp1,pipsTp2,rrTp1,rrTp2,EnumToString(r.sweep_grade),r.bos_strength*100.0,r.time_decay*100.0,r.chase_dist_atr,r.chase_ok?"true":"false",EnumToString(r.news_risk),r.news_label,r.news_minutes_to_event,dec.setup.calibrated_probability,dec.setup.calibration_sample,dec.setup.calibration_has_enough_data?"true":"false");}
string CSignalPublisher::BuildJsonPayload(const TradeDecisionRecord &dec){bool isBuy=(dec.setup.type==ORDER_TYPE_BUY);double entry=isBuy?dec.setup.entry_top:dec.setup.entry_bottom;string dir=isBuy?"BUY":"SELL";string tf=EnumToString((ENUM_TIMEFRAMES)Period());StringReplace(tf,"PERIOD_","");SetupReasons r=dec.setup.reasons;return StringFormat("{\"signal_id\":\"%s\",\"decision_id\":%d,\"symbol\":\"%s\",\"direction\":\"%s\",\"entry\":%.5f,\"invalidation\":%.5f,\"sl\":%.5f,\"tp1\":%.5f,\"tp2\":%.5f,\"final_tp\":%.5f,\"confidence\":%.1f,\"reasons\":%s,\"timeframe\":\"%s\",\"time\":\"%s\",\"regime\":\"%s\",\"session\":\"%s\",\"sweep_grade\":\"%s\",\"htf_ob_aligned\":%s,\"weight_version\":\"%s\",\"extra\":%s}",SignalIdFor(dec.decision_id),dec.decision_id,dec.symbol,dir,entry,dec.setup.invalidation,dec.setup.stop_loss,dec.setup.tp1,dec.setup.tp2,dec.setup.final_tp,dec.setup.confidence,BuildReasonsJsonArray(dec.setup.reasons),tf,TimeToString(dec.decided_time,TIME_DATE|TIME_SECONDS),EnumToString(r.vol_regime),EnumToString(r.session),EnumToString(r.sweep_grade),r.htf_ob_confluence?"true":"false",m_weightVersion,BuildExtraJson(dec));}
bool CSignalPublisher::TransmitOne(string endpoint,const string &payload){uchar rawData[];int len=StringToCharArray(payload,rawData)-1;if(len<0)len=0;ArrayResize(rawData,len);char data[];ArrayResize(data,len);ArrayCopy(data,rawData);char result[];string resultHeaders;string headers="Content-Type: application/json\r\n";if(StringLen(m_apiKey)>0)headers+="X-API-Key: "+m_apiKey+"\r\n";ResetLastError();int status=WebRequest("POST",endpoint,headers,m_timeoutMs,data,result,resultHeaders);if(status==-1){PrintFormat("MedisTouch SignalPublisher: WebRequest to %s failed, error %d.",endpoint,GetLastError());return false;}if(status<200||status>=300){PrintFormat("MedisTouch SignalPublisher: %s responded with HTTP %d.",endpoint,status);return false;}return true;}
bool CSignalPublisher::TransmitOnePatch(string endpoint,const string &payload){uchar rawData[];int len=StringToCharArray(payload,rawData)-1;if(len<0)len=0;ArrayResize(rawData,len);char data[];ArrayResize(data,len);ArrayCopy(data,rawData);char result[];string resultHeaders;string headers="Content-Type: application/json\r\n";if(StringLen(m_apiKey)>0)headers+="X-API-Key: "+m_apiKey+"\r\n";ResetLastError();int status=WebRequest("PATCH",endpoint,headers,m_timeoutMs,data,result,resultHeaders);if(status==-1){PrintFormat("MedisTouch SignalPublisher: lifecycle PATCH to %s failed, error %d.",endpoint,GetLastError());return false;}if(status<200||status>=300){PrintFormat("MedisTouch SignalPublisher: lifecycle PATCH %s responded with HTTP %d.",endpoint,status);return false;}return true;}
bool CSignalPublisher::Publish(const TradeDecisionRecord &dec){if(dec.action!=POLICY_SIGNAL_ONLY&&dec.action!=POLICY_EXECUTE_AND_SIGNAL)return false;if(dec.decision_id==m_lastPublishedId)return false;if(m_fileHandle==INVALID_HANDLE)return false;bool isBuy=(dec.setup.type==ORDER_TYPE_BUY);double entry=isBuy?dec.setup.entry_top:dec.setup.entry_bottom;string dir=isBuy?"BUY":"SELL";string payload=BuildJsonPayload(dec);int targeted=0;int delivered=0;if(m_platform!=NULL){Subscriber subs[];targeted=m_platform.GetActiveSubscribers(subs);for(int i=0;i<targeted;i++){bool ok=TransmitOne(subs[i].endpoint,payload);if(ok)delivered++;m_platform.RecordDelivery(subs[i].id,dec.decision_id,ok);}}FileWrite(m_fileHandle,dec.decision_id,TimeToString(dec.decided_time,TIME_DATE|TIME_MINUTES),dec.symbol,dir,entry,dec.setup.stop_loss,dec.setup.tp1,dec.setup.tp2,dec.setup.final_tp,dec.setup.confidence,EnumToString(dec.action),targeted,delivered);FileFlush(m_fileHandle);m_lastPublishedId=dec.decision_id;return true;}
bool CSignalPublisher::PublishStatusUpdate(long decisionId,string status,string reason){if(m_platform==NULL)return false;string signalId=SignalIdFor(decisionId);string escReason=reason;StringReplace(escReason,"\"","'");string payload=StringFormat("{\"status\":\"%s\",\"reason\":\"%s\"}",status,escReason);Subscriber subs[];int targeted=m_platform.GetActiveSubscribers(subs);bool anyOk=false;for(int i=0;i<targeted;i++){string endpoint=subs[i].endpoint;int pos=StringFind(endpoint,"/signal");if(pos<0)continue;string patchUrl=StringSubstr(endpoint,0,pos)+"/signal/"+signalId+"/status";if(TransmitOnePatch(patchUrl,payload))anyOk=true;}return anyOk;}
string CSignalPublisher::BuildOutcomeJsonPayload(string signalId,string symbol,string direction,string outcome,double realizedR,double mfeR,double maeR,int barsHeld,int barsToFill,bool filled,string regime,string session,string sweepGrade,bool htfObAligned,double confidenceAtSignal,double confidenceDecayed,int decayBars){bool hasR=(outcome!="no_fill"&&outcome!="ambiguous");string realizedRStr=hasR?StringFormat("%.4f",realizedR):"null";string mfeRStr=hasR?StringFormat("%.4f",mfeR):"null";string maeRStr=hasR?StringFormat("%.4f",maeR):"null";return StringFormat("{\"signal_id\":\"%s\",\"symbol\":\"%s\",\"direction\":\"%s\",\"outcome\":\"%s\",\"realized_r\":%s,\"mfe_r\":%s,\"mae_r\":%s,\"bars_held\":%d,\"bars_to_fill\":%d,\"filled\":%s,\"regime\":\"%s\",\"session\":\"%s\",\"sweep_grade\":\"%s\",\"htf_ob_aligned\":%s,\"weight_version\":\"%s\",\"confidence_at_signal\":%.2f,\"confidence_decayed\":%.2f,\"decay_bars\":%d}",signalId,symbol,direction,outcome,realizedRStr,mfeRStr,maeRStr,barsHeld,barsToFill,filled?"true":"false",regime,session,sweepGrade,htfObAligned?"true":"false",m_weightVersion,confidenceAtSignal,confidenceDecayed,decayBars);}
bool CSignalPublisher::PublishOutcome(string signalId,string symbol,string direction,string outcome,double realizedR,double mfeR,double maeR,int barsHeld,int barsToFill,bool filled,string regime,string session,string sweepGrade,bool htfObAligned,double confidenceAtSignal,double confidenceDecayed,int decayBars){if(m_platform==NULL)return false;string payload=BuildOutcomeJsonPayload(signalId,symbol,direction,outcome,realizedR,mfeR,maeR,barsHeld,barsToFill,filled,regime,session,sweepGrade,htfObAligned,confidenceAtSignal,confidenceDecayed,decayBars);Subscriber subs[];int targeted=m_platform.GetActiveSubscribers(subs);bool anyOk=false;for(int i=0;i<targeted;i++){string endpoint=subs[i].endpoint;int pos=StringFind(endpoint,"/signal");if(pos<0)continue;string outcomeUrl=StringSubstr(endpoint,0,pos)+"/outcome";if(TransmitOne(outcomeUrl,payload))anyOk=true;}return anyOk;}
#endif
//+------------------------------------------------------------------+
