//+------------------------------------------------------------------+
//|                                       Execution/BrokerAdapter.mqh |
//+------------------------------------------------------------------+
#ifndef BROKERADAPTER_MQH
#define BROKERADAPTER_MQH
#include <Trade\Trade.mqh>
class CBrokerAdapter
  {
private:
   CTrade m_trade; int m_maxRetries; int m_retryDelayMs; ulong m_lastLatencyUs;
   bool LastRequestOk(string action); ulong ResolvePositionTicket(); bool IsRetryable(uint retcode); int DelayForRetcode(uint retcode); bool IsConnected();
   bool IsMarketOpenForTrading(string symbol,bool requireFullOpen,bool isBuy=true); bool ValidateStopDistance(string symbol,double refPrice,double sl,double tp,bool isBuy,string action);
public:
   void Init(ulong magic,int maxRetries=3,int retryDelayMs=300); double LastLatencyMs(){return(double)m_lastLatencyUs/1000.0;}
   bool MarketBuy(string symbol,double volume,double sl,double tp,ulong &ticketOut,double &fillPriceOut,string comment="");
   bool MarketSell(string symbol,double volume,double sl,double tp,ulong &ticketOut,double &fillPriceOut,string comment="");
   bool PlaceLimit(string symbol,ENUM_ORDER_TYPE type,double volume,double price,double sl,double tp,ulong &ticketOut,string comment="");
   bool CancelOrder(ulong ticket); bool ModifySLTP(ulong ticket,double sl,double tp); bool ClosePartial(ulong ticket,double volume); bool CloseFull(ulong ticket);
  };
void CBrokerAdapter::Init(ulong magic,int maxRetries,int retryDelayMs){m_trade.SetExpertMagicNumber(magic);m_trade.SetDeviationInPoints(20);m_trade.SetTypeFillingBySymbol(_Symbol);m_maxRetries=MathMax(1,maxRetries);m_retryDelayMs=MathMax(0,retryDelayMs);m_lastLatencyUs=0;}
// Retry only explicit transient conditions. Unknown codes fail closed because
// a second request after an ambiguous broker response can duplicate exposure.
bool CBrokerAdapter::IsRetryable(uint retcode){switch(retcode){case TRADE_RETCODE_REQUOTE:case TRADE_RETCODE_PRICE_CHANGED:case TRADE_RETCODE_PRICE_OFF:case TRADE_RETCODE_CONNECTION:case TRADE_RETCODE_TIMEOUT:return true;default:return false;}}
int CBrokerAdapter::DelayForRetcode(uint retcode){switch(retcode){case TRADE_RETCODE_REQUOTE:case TRADE_RETCODE_PRICE_CHANGED:case TRADE_RETCODE_PRICE_OFF:return MathMin(m_retryDelayMs,50);case TRADE_RETCODE_CONNECTION:case TRADE_RETCODE_TIMEOUT:return MathMax(m_retryDelayMs,500);default:return m_retryDelayMs;}}
bool CBrokerAdapter::IsConnected(){if(TerminalInfoInteger(TERMINAL_CONNECTED))return true;Print("MedisTouch BrokerAdapter: terminal not connected to the trade server — refusing to submit.");return false;}
bool CBrokerAdapter::IsMarketOpenForTrading(string symbol,bool requireFullOpen,bool isBuy){long mode=(long)SymbolInfoInteger(symbol,SYMBOL_TRADE_MODE);if(mode==SYMBOL_TRADE_MODE_DISABLED)return false;if(requireFullOpen&&mode==SYMBOL_TRADE_MODE_CLOSEONLY)return false;if(requireFullOpen&&mode==SYMBOL_TRADE_MODE_LONGONLY&&!isBuy)return false;if(requireFullOpen&&mode==SYMBOL_TRADE_MODE_SHORTONLY&&isBuy)return false;return true;}
bool CBrokerAdapter::ValidateStopDistance(string symbol,double refPrice,double sl,double tp,bool isBuy,string action){if(refPrice<=0.0)return false;double point=SymbolInfoDouble(symbol,SYMBOL_POINT);if(point<=0.0)return false;long stops=SymbolInfoInteger(symbol,SYMBOL_TRADE_STOPS_LEVEL);long freeze=SymbolInfoInteger(symbol,SYMBOL_TRADE_FREEZE_LEVEL);double minDist=MathMax(stops,freeze)*point;if(sl>0.0){bool wrong=isBuy?(sl>=refPrice):(sl<=refPrice);if(wrong||(minDist>0.0&&MathAbs(refPrice-sl)<minDist))return false;}if(tp>0.0){bool wrong=isBuy?(tp<=refPrice):(tp>=refPrice);if(wrong||(minDist>0.0&&MathAbs(refPrice-tp)<minDist))return false;}return true;}
bool CBrokerAdapter::LastRequestOk(string action){uint code=m_trade.ResultRetcode();if(code==TRADE_RETCODE_DONE||code==TRADE_RETCODE_PLACED||code==TRADE_RETCODE_DONE_PARTIAL)return true;PrintFormat("MedisTouch BrokerAdapter: %s failed, retcode=%d (%s)",action,code,m_trade.ResultRetcodeDescription());return false;}
ulong CBrokerAdapter::ResolvePositionTicket(){ulong deal=m_trade.ResultDeal();if(deal==0)return m_trade.ResultOrder();if(!HistoryDealSelect(deal))return m_trade.ResultOrder();ulong pos=(ulong)HistoryDealGetInteger(deal,DEAL_POSITION_ID);return pos>0?pos:m_trade.ResultOrder();}
bool CBrokerAdapter::MarketBuy(string symbol,double volume,double sl,double tp,ulong &ticketOut,double &fillPriceOut,string comment){ticketOut=0;fillPriceOut=0.0;if(!IsConnected()||!IsMarketOpenForTrading(symbol,true,true))return false;double ref=SymbolInfoDouble(symbol,SYMBOL_ASK);if(!ValidateStopDistance(symbol,ref,sl,tp,true,"MarketBuy"))return false;ulong t0=GetMicrosecondCount();for(int i=0;i<m_maxRetries;i++){if(m_trade.Buy(volume,symbol,0.0,sl,tp,comment)&&LastRequestOk("MarketBuy")){ticketOut=ResolvePositionTicket();fillPriceOut=m_trade.ResultPrice();m_lastLatencyUs=GetMicrosecondCount()-t0;return ticketOut>0;}uint code=m_trade.ResultRetcode();if(!IsRetryable(code))break;Sleep(DelayForRetcode(code));}m_lastLatencyUs=GetMicrosecondCount()-t0;return false;}
bool CBrokerAdapter::MarketSell(string symbol,double volume,double sl,double tp,ulong &ticketOut,double &fillPriceOut,string comment){ticketOut=0;fillPriceOut=0.0;if(!IsConnected()||!IsMarketOpenForTrading(symbol,true,false))return false;double ref=SymbolInfoDouble(symbol,SYMBOL_BID);if(!ValidateStopDistance(symbol,ref,sl,tp,false,"MarketSell"))return false;ulong t0=GetMicrosecondCount();for(int i=0;i<m_maxRetries;i++){if(m_trade.Sell(volume,symbol,0.0,sl,tp,comment)&&LastRequestOk("MarketSell")){ticketOut=ResolvePositionTicket();fillPriceOut=m_trade.ResultPrice();m_lastLatencyUs=GetMicrosecondCount()-t0;return ticketOut>0;}uint code=m_trade.ResultRetcode();if(!IsRetryable(code))break;Sleep(DelayForRetcode(code));}m_lastLatencyUs=GetMicrosecondCount()-t0;return false;}
bool CBrokerAdapter::PlaceLimit(string symbol,ENUM_ORDER_TYPE type,double volume,double price,double sl,double tp,ulong &ticketOut,string comment){ticketOut=0;if(type!=ORDER_TYPE_BUY_LIMIT&&type!=ORDER_TYPE_SELL_LIMIT)return false;bool buy=(type==ORDER_TYPE_BUY_LIMIT);if(!IsConnected()||!IsMarketOpenForTrading(symbol,true,buy)||!ValidateStopDistance(symbol,price,sl,tp,buy,"PlaceLimit"))return false;ulong t0=GetMicrosecondCount();for(int i=0;i<m_maxRetries;i++){bool ok=buy?m_trade.BuyLimit(volume,price,symbol,sl,tp,ORDER_TIME_GTC,0,comment):m_trade.SellLimit(volume,price,symbol,sl,tp,ORDER_TIME_GTC,0,comment);if(ok&&LastRequestOk("PlaceLimit")){ticketOut=m_trade.ResultOrder();m_lastLatencyUs=GetMicrosecondCount()-t0;return ticketOut>0;}uint code=m_trade.ResultRetcode();if(!IsRetryable(code))break;Sleep(DelayForRetcode(code));}m_lastLatencyUs=GetMicrosecondCount()-t0;return false;}
bool CBrokerAdapter::CancelOrder(ulong ticket){if(!IsConnected())return false;if(m_trade.OrderDelete(ticket))return true;LastRequestOk("CancelOrder");return false;}
bool CBrokerAdapter::ModifySLTP(ulong ticket,double sl,double tp){if(!IsConnected()||!PositionSelectByTicket(ticket))return false;string symbol=PositionGetString(POSITION_SYMBOL);bool buy=(PositionGetInteger(POSITION_TYPE)==POSITION_TYPE_BUY);double ref=buy?SymbolInfoDouble(symbol,SYMBOL_BID):SymbolInfoDouble(symbol,SYMBOL_ASK);if(!ValidateStopDistance(symbol,ref,sl,tp,buy,"ModifySLTP"))return false;if(m_trade.PositionModify(ticket,sl,tp))return true;LastRequestOk("ModifySLTP");return false;}
bool CBrokerAdapter::ClosePartial(ulong ticket,double volume){if(!IsConnected()||!PositionSelectByTicket(ticket))return false;if(m_trade.PositionClosePartial(ticket,volume))return true;LastRequestOk("ClosePartial");return false;}
bool CBrokerAdapter::CloseFull(ulong ticket){if(!IsConnected()||!PositionSelectByTicket(ticket))return false;if(m_trade.PositionClose(ticket))return true;LastRequestOk("CloseFull");return false;}
#endif
//+------------------------------------------------------------------+
